
package pl.edu.agh.mic.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Thu Dec 05 18:57:00 CET 2013
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "addTicket", namespace = "http://ws.mic.agh.edu.pl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addTicket", namespace = "http://ws.mic.agh.edu.pl/", propOrder = {"description", "createdBy"})

public class AddTicket {

    @XmlElement(name = "description", required = true)
    private java.lang.String description;
    @XmlElement(name = "createdBy", required = true)
    private java.lang.String createdBy;

    public java.lang.String getDescription() {
        return this.description;
    }

    public void setDescription(java.lang.String newDescription)  {
        this.description = newDescription;
    }

    public java.lang.String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(java.lang.String newCreatedBy)  {
        this.createdBy = newCreatedBy;
    }

}

