
package pl.edu.agh.mic.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Thu Dec 05 18:57:00 CET 2013
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "evalEta", namespace = "http://ws.mic.agh.edu.pl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "evalEta", namespace = "http://ws.mic.agh.edu.pl/", propOrder = {"ticketId", "time"})

public class EvalEta {

    @XmlElement(name = "ticketId", required = true)
    private java.lang.String ticketId;
    @XmlElement(name = "time", required = true)
    private java.util.Date time;

    public java.lang.String getTicketId() {
        return this.ticketId;
    }

    public void setTicketId(java.lang.String newTicketId)  {
        this.ticketId = newTicketId;
    }

    public java.util.Date getTime() {
        return this.time;
    }

    public void setTime(java.util.Date newTime)  {
        this.time = newTime;
    }

}

