
package pl.edu.agh.mic.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.11
 * Thu Dec 05 21:47:47 CET 2013
 * Generated source version: 2.6.11
 */

@XmlRootElement(name = "getAttachmentResponse", namespace = "http://ws.mic.agh.edu.pl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAttachmentResponse", namespace = "http://ws.mic.agh.edu.pl/")

public class GetAttachmentResponse {

    @XmlElement(name = "return")
    private pl.edu.agh.mic.model.Attachment _return;

    public pl.edu.agh.mic.model.Attachment getReturn() {
        return this._return;
    }

    public void setReturn(pl.edu.agh.mic.model.Attachment new_return)  {
        this._return = new_return;
    }

}

