
package pl.edu.agh.mic.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Thu Dec 05 18:57:00 CET 2013
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "getTicketResponse", namespace = "http://ws.mic.agh.edu.pl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTicketResponse", namespace = "http://ws.mic.agh.edu.pl/")

public class GetTicketResponse {

    @XmlElement(name = "return")
    private pl.edu.agh.mic.model.Ticket _return;

    public pl.edu.agh.mic.model.Ticket getReturn() {
        return this._return;
    }

    public void setReturn(pl.edu.agh.mic.model.Ticket new_return)  {
        this._return = new_return;
    }

}

