
package pl.edu.agh.mic.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Thu Dec 05 18:57:00 CET 2013
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "listTickets", namespace = "http://ws.mic.agh.edu.pl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listTickets", namespace = "http://ws.mic.agh.edu.pl/")

public class ListTickets {

    @XmlElement(name = "decidedByUserId", required = true)
    private java.lang.String decidedByUserId;

    public java.lang.String getDecidedByUserId() {
        return this.decidedByUserId;
    }

    public void setDecidedByUserId(java.lang.String newDecidedByUserId)  {
        this.decidedByUserId = newDecidedByUserId;
    }

}

