
package pl.edu.agh.mic.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.11
 * Fri Dec 06 01:06:13 CET 2013
 * Generated source version: 2.6.11
 */

@XmlRootElement(name = "listTickets", namespace = "http://ws.mic.agh.edu.pl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listTickets", namespace = "http://ws.mic.agh.edu.pl/")

public class ListTickets {

    @XmlElement(name = "ownedByUserId")
    private java.lang.String ownedByUserId;

    public java.lang.String getOwnedByUserId() {
        return this.ownedByUserId;
    }

    public void setOwnedByUserId(java.lang.String newOwnedByUserId)  {
        this.ownedByUserId = newOwnedByUserId;
    }

}

